DEFAULT_VALUES = {
    "use_normalization_json": "examples/data/phase_3/phase_3_debug_out.json",
    "x_train_file": "examples/data/phase_3/normalized_d1.csv",
    "y_train_file": "examples/data/phase_3/normalized_d1.csv",
    "x_validation_file": "examples/data/phase_3/normalized_d2.csv",
    "y_validation_file": "examples/data/phase_3/normalized_d2.csv",
    "x_test_file": "examples/data/phase_3/normalized_d3.csv",
    "y_test_file": "examples/data/phase_3/normalized_d3.csv",
    "output_file": "examples/results/phase_3_2/phase_3_2_cnn_25200_1h_prediction.csv",
    "results_file": "examples/results/phase_3_2/phase_3_2_cnn_25200_1h_results.csv",
    "loss_plot_file": "examples/results/phase_3_2/phase_3_2_cnn_25200_1h_loss_plot.png",
    "model_plot_file": "examples/results/phase_3_2/phase_3_2_cnn_1h_model_plot.png",
    "uncertainties_file": "examples/results/phase_3_2/phase_3_2_cnn_25200_1h_uncertanties.csv",
    "predictions_plot_file": "examples/results/phase_3_2/phase_3_2_cnn_25200_1h_predictions_plot.png",
    "stl_plot_file": "examples/results/phase_3_2/phase_3_2_25200_1h_stl_decomposition_plot.png",
    "wavelet_plot_file": "examples/results/phase_3_2/phase_3_2_25200_1h_wavelet_decomposition_plot.png",
    "tapper_plot_file": "examples/results/phase_3_2/phase_3_2_25200_1h_multi_tapper_decomposition_plot.png",
    "target_column": "CLOSE",
    'output_file': './csv_output.csv',
    'save_encoder': 'examples/results/phase_3_2/phase_3_2_cnn_25200_1h_encoder_model.h5',
    'save_decoder': 'examples/results/phase_3_2/phase_3_2_cnn_25200_1h_decoder_model.h5',
    'load_encoder': None,
    'load_decoder': None,
    'evaluate_encoder': './encoder_eval.csv',
    'evaluate_decoder': './decoder_eval.csv',
    "preprocessor_plugin": "stl_preprocessor",
    'encoder_plugin': 'cnn',
    'decoder_plugin': 'cnn',
    'use_sliding_windows': False,
    'quiet_mode': False,
    'force_date': False,
    'headers': True,
    'input_offset': 0,
    'window_size': 256,  # Number of time steps in each window (e.g., 24 for daily patterns)
    'l2_reg': 1e-4,          # L2 regularization factor
    'early_patience': 30,           # Early stopping patience
    'max_steps_train': 6300,
    'max_steps_val': 6300,
    'max_steps_test': 6300,
    'iterations': 1,
    'epochs': 1000,
    'uncertainty_file': 'prediction_uncertainties.csv',
    'batch_size': 32,
    'use_sliding_window' : False,
    "kl_weight": 1e-6,
    "kl_anneal_epochs": 100,        
    "kl_beta_start": 0.0001,        # Starting value for KL beta annealing
    "kl_beta": 1.0,                 # Final value for KL beta (used as kl_beta_end by annealing)
    "kl_anneal_epochs": 100,  
    "mmd_lambda": 0.1,
    "overfitting_penalty": 0.1,
    "use_returns": True,
    "mc_samples":100,
    "plotted_horizon": 6,
    "start_from_epoch": 10,
    "plot_color_predicted": "orange",
    "plot_color_true": "blue",
    "plot_color_uncertainty": "green",
    "uncertainty_color_alpha": 0.01,
    "min_delta": 1e-5,
    "plot_points": 240,
    "use_strategy": False,
    "strategy_plugin_group": "heuristic_strategy.plugins",
    "strategy_plugin_name": "ls_pred_strategy",
    "strategy_1h_prediction": "examples/results/phase_1/phase_1_cnn_25200_1h_prediction.csv",
    "strategy_1h_uncertainty": "examples/results/phase_1/phase_1_cnn_25200_1h_uncertanties.csv",
    "strategy_base_dataset": "examples/data/phase_1/phase_1_base_d3.csv",
    "strategy_load_parameters": "examples/data/phase_1/strategy_parameters.json",
    "target_scaling_factor":1000,
    "optimizer_output_file": "optimizer_output.json",
    "penalty_close_lambda":0.0001, # penalty in thel loss function for the predicted value being 0 (Naive)
    "penalty_far_lambda":0.0001,
    'threshold_error': 0.5,
    'initial_size': 48, #initial interface size for incremental/decremmental search (NOT USED)
    "interface_size": 48, # not used
    'step_size': 2,
    'save_log': './debug_out.json',
    'remote_log': None,
    'remote_load_config': None,
    'remote_save_config': None,
    'username': None,
    'password': None, 
    'load_config': None,
    'save_config': './config_out.json',
    'quiet_mode': False,
    'force_date': True,
    'incremental_search': True, # if false performs decresing search instead
    'headers': True,
    'dataset_periodicity': '1h',  # Add dataset_periodicity here, can be 1m, 5m, 15m, 30m, 1h, 4h, daily
    "mmd_sigma": 1.0,
    "mmd_weight": 1.0,
    "rnn_hidden_dim": 64,
    "conditioning_dim": 10,
    "latent_dim": 32,

    "use_daily": False,
    "max_steps_train": 25200,
    "max_steps_test": 6300,
    "intermediate_layers": 2,
    "initial_layer_size": 128,
    "layer_size_divisor": 2,
    "learning_rate": 1e-4,
    "activation": "tanh",
    "l2_reg": 1e-6,
    "early_patience": 40,
    "start_from_epoch": 15,
    "use_returns": True,
    "mc_samples":20,
    "plotted_horizon": 6,
    "mmd_lambda": 1e-2,
    "window_size": 288,
    "batch_size": 128,
    "plot_color_predicted": "red",
    "plot_color_true": "blue",
    "plot_color_uncertainty": "green",
    "plot_color_target": "orange",
    "uncertainty_color_alpha": 0.01,
    "plot_points": 48,
    "min_delta": 1e-7,
    "epochs": 1000,
    "use_strategy": False,
    "stl_period":24,
    "predicted_horizons": [1,2,3,4,5,6],
    "use_stl": True,
    "use_wavelets": True,
    "use_multi_tapper": True
    
}

