DEFAULT_VALUES = {
    "use_normalization_json": "examples/data/phase_3/phase_3_debug_out.json",
    "x_train_file": "examples/data/phase_3/normalized_d1.csv",
    "y_train_file": "examples/data/phase_3/normalized_d1.csv",
    "x_validation_file": "examples/data/phase_3/normalized_d2.csv",
    "y_validation_file": "examples/data/phase_3/normalized_d2.csv",
    "x_test_file": "examples/data/phase_3/normalized_d3.csv",
    "y_test_file": "examples/data/phase_3/normalized_d3.csv",
    "output_file": "examples/results/phase_3_1/phase_3_1_cnn_25200_1h_prediction.csv",
    "results_file": "examples/results/phase_3_1/phase_3_1_cnn_25200_1h_results.csv",
    "loss_plot_file": "examples/results/phase_3_1/phase_3_1_cnn_25200_1h_loss_plot.png",
    "model_plot_file": "examples/results/phase_3_1/phase_3_1_cnn_1h_model_plot.png",
    "uncertainties_file": "examples/results/phase_3_1/phase_3_1_cnn_25200_1h_uncertanties.csv",
    "predictions_plot_file": "examples/results/phase_3_1/phase_3_1_cnn_25200_1h_predictions_plot.png",
    "stl_plot_file": "examples/results/phase_3_1/phase_3_1_25200_1h_stl_decomposition_plot.png",
    "wavelet_plot_file": "examples/results/phase_3_1/phase_3_1_25200_1h_wavelet_decomposition_plot.png",
    "tapper_plot_file": "examples/results/phase_3_1/phase_3_1_25200_1h_multi_tapper_decomposition_plot.png",
    "target_column": "CLOSE",
    'output_file': './csv_output.csv',
    'save_encoder': 'examples/results/phase_3_1/phase_3_1_cnn_25200_1h_encoder_model.h5',
    'save_decoder': 'examples/results/phase_3_1/phase_3_1_cnn_25200_1h_decoder_model.h5',
    'load_encoder': None,
    'load_decoder': None,
    'evaluate_encoder': './encoder_eval.csv',
    'evaluate_decoder': './decoder_eval.csv',
    "preprocessor_plugin": "stl_preprocessor",
    'encoder_plugin': 'cnn',
    'decoder_plugin': 'cnn',
    'use_sliding_windows': True,
    'threshold_error': 0.5,
    'initial_size': 48, #initial interface size for incremental/decremmental search (NOT USED)
    "interface_size": 48, # not used
    'step_size': 2,
    'save_log': './debug_out.json',
    'remote_log': None,
    'remote_load_config': None,
    'remote_save_config': None,
    'username': None,
    'password': None, 
    'load_config': None,
    'save_config': './config_out.json',
    'quiet_mode': False,
    'force_date': True,
    'incremental_search': True, # if false performs decresing search instead
    'headers': True,
    'dataset_periodicity': '1h',  # Add dataset_periodicity here, can be 1m, 5m, 15m, 30m, 1h, 4h, daily
    "mmd_sigma": 1.0,
    "mmd_weight": 1.0,

    
    "use_daily": False,
    "max_steps_train": 25200,
    "max_steps_test": 6300,
    "intermediate_layers": 2,
    "initial_layer_size": 48,
    "layer_size_divisor": 2,
    "learning_rate": 1e-3,
    "activation": "tanh",
    "l2_reg": 1e-6,
    "early_patience": 40,
    "start_from_epoch": 15,
    "use_returns": True,
    "mc_samples":20,
    "plotted_horizon": 6,
    "mmd_lambda": 1e-2,
    "window_size": 144,
    "batch_size": 128,
    "plot_color_predicted": "red",
    "plot_color_true": "blue",
    "plot_color_uncertainty": "green",
    "plot_color_target": "orange",
    "uncertainty_color_alpha": 0.01,
    "plot_points": 48,
    "min_delta": 1e-7,
    "epochs": 200,
    "use_strategy": False,
    "stl_period":24,
    "predicted_horizons": [1,2,3,4,5,6],
    "use_stl": True,
    "use_wavelets": True,
    "use_multi_tapper": True
    
}

