"""Phase-4 extractibility: three paired arms on one feature, one TRAIN fold (plan 2026-10-06, section 2).

Data contract reused from app.univariate_temporal (lane D): standardized signal, observed_mask,
causal delta_time and known calendar encodings on an hourly grid; the forecast target never enters.

Corpus identity is pinned here (CORPORA): a parquet whose digest differs from the registry is
refused before any value is read.  Every feature resolves from the governed PS1 TRAIN parquets
(EURUSD) or the governed phase-1 ETH TRAIN parquet; PS2 batches are never read.

Fold rule (identical to the PS2 batch manifests): val = decision rows of calendar year Y inside
TRAIN; fit = [first row + 720h, val_start - 720h - 1h].  Rows after the fold's val range are never
windowed, so perturbing them cannot change a terminal (FS4-03).

Architecture: causal Conv1D encoder with temporal reduction 24 -> 12 -> 6 (latent (B, 6, D)),
symmetric decoder 6 -> 12 -> 24.  Initial weights are generated by numpy from the task seed so
RANDOM_ENCODER and TRAINED_ENCODER share bit-identical initial weights on any device.

Scoring rows (val origins with an observed value at the origin), the corruption mask and the
paired naive derive from (population, identity, feature, fold, seed) and never from the arm, so
the three arms share rows_sha256, mask_sha256 and population_n (FS4-09).
"""
from __future__ import annotations

import datetime as _dt
import hashlib
import json
import os
import time
from dataclasses import asdict, dataclass
from typing import Dict, List, Optional, Sequence, Tuple

import numpy as np

from app import univariate_temporal as U

ARMS = ("RAW", "RANDOM_ENCODER", "TRAINED_ENCODER")
GRID_SECONDS = 3600
WINDOW = 24
FOLD_GAP_HOURS = 720
FOLD_YEARS = {"inner_2019": 2019, "inner_2020": 2020, "inner_2021": 2021,
              "inner_2022": 2022, "inner_2023": 2023}
TIMESTAMP_COLUMN = "t_decision_utc"
ARCHITECTURE_ID = "fs4_causal_conv_24_12_6_v1"

# Pinned governed TRAIN corpora.  identity -> roles -> expected sha256.  Values verified on the
# coordinator, worker_a and worker_b on 2026-10-07 (identical digests on the three hosts).
CORPORA = {
    "phase1-eurusd-final:94d20c038d55e152": {
        "population_id": "EURUSD", "bar_seconds": 3600,
        "files": {
            "eurusd_ps1_batch_001": "bd005701247dc181c81457037cbad6e6142f8171ad8c3595f1cd489986557aa2",
            "eurusd_ps1_batch_002": "0e6ff8c570804823921227bd6733b185c17e54808364735067953f524f4399f3",
            "eurusd_ps1_batch_003": "fd0b4423db991cfb05cd4f9357a378648579d4c11552a1cac413ed711c3520bc",
        },
    },
    "phase1-final:ETH:29d2f745f5d9e87c": {
        "population_id": "ETH", "bar_seconds": 14400,
        "files": {
            "eth_train": "641c371af53ad8c3d03fb6833d7c794a11e0b37bde95c4daee5efb0b5516b30c",
        },
    },
}


@dataclass(frozen=True)
class Hyper:
    window: int = WINDOW
    latent_steps: int = 6
    latent_dim: int = 8
    filters: int = 16
    kernel_size: int = 3
    hide_fraction: float = 0.25
    min_observed_per_window: int = 4
    min_scoring_windows: int = 64
    min_fit_windows: int = 256
    es_tail_fraction: float = 0.1
    es_purge_hours: int = 168
    batch_size: int = 64
    learning_rate: float = 1e-3
    max_epochs: int = 100
    patience: int = 10
    max_fit_windows: int = 0  # 0 = all fit origins; else an evenly spaced subset (cost control only)

    def to_dict(self) -> dict:
        return asdict(self)


class Refusal(U.ContractError):
    """Typed refusal; the code is the first token of the message."""

    def __init__(self, code: str, detail: str = ""):
        self.code = code
        super().__init__(f"{code}: {detail}" if detail else code)


def canonical(value) -> str:
    return json.dumps(value, sort_keys=True, separators=(",", ":"), allow_nan=False)


def digest(value) -> str:
    return hashlib.sha256(canonical(value).encode()).hexdigest()


def task_digest(payload: dict) -> str:
    keys = ("schema", "population_id", "identity", "feature_id", "fold_id", "arm", "seed")
    return digest({k: payload[k] for k in keys})


# --------------------------------------------------------------------------- corpus
def _parse_utc(values) -> np.ndarray:
    """Timestamps (tz-aware, naive-UTC or ISO strings) -> int64 epoch seconds."""
    arr = np.asarray(values)
    if np.issubdtype(arr.dtype, np.datetime64):
        return arr.astype("datetime64[s]").astype(np.int64)
    out = np.empty(arr.shape[0], np.int64)
    for i, v in enumerate(arr.tolist()):
        if isinstance(v, (int, np.integer)):
            out[i] = int(v)
            continue
        if hasattr(v, "timestamp"):
            if getattr(v, "tzinfo", None) is None:
                v = v.replace(tzinfo=_dt.timezone.utc)
            out[i] = int(v.timestamp())
            continue
        s = str(v).strip().replace("T", " ")
        if s.endswith("Z"):
            s = s[:-1]
        d = _dt.datetime.fromisoformat(s)
        if d.tzinfo is None:
            d = d.replace(tzinfo=_dt.timezone.utc)
        out[i] = int(d.timestamp())
    return out


class Corpus:
    """One governed TRAIN population: decision timestamps + one feature column at a time."""

    def __init__(self, identity: str, inputs: Dict[str, str], registry: Optional[dict] = None):
        reg = CORPORA if registry is None else registry
        if identity not in reg:
            raise Refusal("UNKNOWN_IDENTITY", identity)
        spec = reg[identity]
        self.identity, self.population_id, self.bar_seconds = identity, spec["population_id"], int(spec["bar_seconds"])
        self.files: Dict[str, str] = {}
        self.file_sha256: Dict[str, str] = {}
        for role, expected in spec["files"].items():
            path = inputs.get(role)
            if not path or not os.path.isfile(path):
                raise Refusal("CORPUS_FILE_MISSING", f"{role} -> {path!r}")
            actual = U.sha256_file(path)
            if actual != expected:
                raise Refusal("CORPUS_DIGEST_MISMATCH", f"{role}: {actual} != pinned {expected}")
            self.files[role], self.file_sha256[role] = path, actual
        import pyarrow.parquet as pq
        self._schemas = {role: pq.ParquetFile(path).schema_arrow.names for role, path in self.files.items()}
        self.ts: Optional[np.ndarray] = None
        self._tables: Dict[str, object] = {}

    def columns(self) -> Dict[str, List[str]]:
        """feature -> roles holding it (timestamp/row_id excluded)."""
        out: Dict[str, List[str]] = {}
        for role, names in self._schemas.items():
            for n in names:
                if n not in (TIMESTAMP_COLUMN, "row_id"):
                    out.setdefault(n, []).append(role)
        return out

    def _table(self, role: str):
        if role not in self._tables:
            import pyarrow.parquet as pq
            self._tables[role] = pq.read_table(self.files[role])
        return self._tables[role]

    def timestamps(self) -> np.ndarray:
        if self.ts is None:
            ref = None
            for role in self.files:
                t = self._table(role)
                if TIMESTAMP_COLUMN not in t.column_names:
                    raise Refusal("TIMESTAMP_COLUMN_MISSING", role)
                ts = _parse_utc(t[TIMESTAMP_COLUMN].to_numpy())
                if ts.ndim != 1 or ts.size < 2 or np.any(np.diff(ts) <= 0):
                    raise Refusal("TIMESTAMPS_NOT_STRICTLY_INCREASING", role)
                if ref is not None and not np.array_equal(ref, ts):
                    raise Refusal("CORPUS_ROWS_DISAGREE", f"{role} rows differ from the first file")
                ref = ts
            self.ts = ref
        return self.ts

    def feature(self, feature_id: str) -> Tuple[np.ndarray, str, str]:
        """(values float64 with NaN = unobserved, role, column_sha256). Target-like names refused."""
        U.check_no_target([feature_id])
        U.check_not_economic_series(feature_id)
        roles = self.columns().get(feature_id)
        if not roles:
            raise Refusal("FEATURE_NOT_IN_CORPUS", f"{feature_id} not in {sorted(self.files)}")
        role = roles[0]
        col = self._table(role)[feature_id]
        try:
            values = np.asarray(col.to_numpy(zero_copy_only=False), dtype=np.float64)
        except (TypeError, ValueError) as exc:
            raise Refusal("FEATURE_NOT_NUMERIC", f"{feature_id}: {exc}") from exc
        if len(roles) > 1:
            for other in roles[1:]:
                v2 = np.asarray(self._table(other)[feature_id].to_numpy(zero_copy_only=False), np.float64)
                if not np.array_equal(np.nan_to_num(values, nan=-1e300), np.nan_to_num(v2, nan=-1e300)):
                    raise Refusal("FEATURE_AMBIGUOUS_ACROSS_FILES", f"{feature_id} differs between {roles}")
        ts = self.timestamps()
        h = hashlib.sha256()
        h.update(np.ascontiguousarray(ts, dtype="<i8").tobytes())
        h.update(np.ascontiguousarray(values, dtype="<f8").tobytes())
        return values, role, h.hexdigest()


# --------------------------------------------------------------------------- grid and folds
@dataclass
class Grid:
    ts: np.ndarray            # regular hourly grid, int64 seconds
    row_index: np.ndarray     # grid index of every decision row
    x: np.ndarray             # float64 on the grid, NaN where no row / unobserved
    observed: np.ndarray      # bool on the grid


def to_grid(ts_rows: np.ndarray, values: np.ndarray) -> Grid:
    ts_rows = np.asarray(ts_rows, np.int64)
    if np.any((ts_rows - ts_rows[0]) % GRID_SECONDS != 0):
        raise Refusal("GRID_MISALIGNED", f"decision rows are not on the {GRID_SECONDS}s grid")
    n = int((ts_rows[-1] - ts_rows[0]) // GRID_SECONDS) + 1
    grid = ts_rows[0] + GRID_SECONDS * np.arange(n, dtype=np.int64)
    idx = ((ts_rows - ts_rows[0]) // GRID_SECONDS).astype(np.int64)
    x = np.full(n, np.nan)
    x[idx] = np.asarray(values, np.float64)
    return Grid(grid, idx, x, np.isfinite(x))


def _year_start(year: int) -> int:
    return int(_dt.datetime(year, 1, 1, tzinfo=_dt.timezone.utc).timestamp())


def fold_spec(fold_id: str, ts_rows: np.ndarray) -> U.FoldSpec:
    """Calendar-year inner fold inside TRAIN, same rule as the PS2 batch manifests."""
    if fold_id not in FOLD_YEARS:
        raise Refusal("UNKNOWN_FOLD", fold_id)
    year = FOLD_YEARS[fold_id]
    train_end = int(ts_rows[-1])
    in_year = ts_rows[(ts_rows >= _year_start(year)) & (ts_rows < _year_start(year + 1)) & (ts_rows <= train_end)]
    if in_year.size == 0:
        raise Refusal("NOT_AVAILABLE_FOR_TRAIN", f"{fold_id}: no TRAIN decision rows in {year}")
    val = (int(in_year[0]), int(in_year[-1]))
    gap = FOLD_GAP_HOURS * 3600
    fit = (int(ts_rows[0]) + gap, val[0] - gap - GRID_SECONDS)
    if fit[0] > fit[1]:
        raise Refusal("NOT_AVAILABLE_FOR_TRAIN", f"{fold_id}: fit range empty before {year}")
    return U.FoldSpec(fold_id, "train", fit, val)


def origins(grid: Grid, rng: Tuple[int, int], hp: Hyper) -> np.ndarray:
    """Decision rows inside rng with an observed value at the origin and a full window of history."""
    idx = grid.row_index
    ts = grid.ts[idx]
    keep = (ts >= rng[0]) & (ts <= rng[1]) & grid.observed[idx] & (idx >= hp.window - 1)
    cand = idx[keep]
    if cand.size == 0:
        return cand
    w = hp.window
    counts = np.array([grid.observed[i - w + 1: i + 1].sum() for i in cand])
    return cand[counts >= hp.min_observed_per_window]


def even_subset(idx: np.ndarray, cap: int) -> np.ndarray:
    if cap <= 0 or idx.size <= cap:
        return idx
    return idx[np.unique(np.linspace(0, idx.size - 1, cap).round().astype(int))]


# --------------------------------------------------------------------------- masks, naive, scoring
def _seed_from(parts: dict) -> int:
    return int(digest(parts)[:16], 16) % (2 ** 63)


def hidden_mask(observed: np.ndarray, seed: int, fraction: float) -> np.ndarray:
    """Hide round(fraction * n_observed) >= 1 observed points per window; (B, T) bool."""
    obs = np.asarray(observed, bool)
    if obs.ndim == 3:
        obs = obs[..., 0]
    rng = np.random.default_rng(seed)
    score = rng.random(obs.shape)
    score[~obs] = np.inf
    order = np.argsort(score, axis=1)
    n_obs = obs.sum(axis=1)
    k = np.maximum(1, np.rint(fraction * n_obs).astype(int))
    k = np.minimum(k, np.maximum(n_obs - 1, 0))  # keep at least one visible point when possible
    rank = np.empty_like(order)
    rows = np.arange(obs.shape[0])[:, None]
    rank[rows, order] = np.arange(obs.shape[1])[None, :]
    return (rank < k[:, None]) & obs


def mask_sha256(hidden: np.ndarray) -> str:
    h = hashlib.sha256()
    h.update(str(hidden.shape).encode())
    h.update(np.ascontiguousarray(hidden, dtype=np.uint8).tobytes())
    return h.hexdigest()


def corrupt(batch: U.TemporalBatch, hidden: np.ndarray) -> U.TemporalBatch:
    """Hidden points become unobserved (signal 0, mask 0); delta_time stays as observed-history says."""
    c = batch.copy_arrays()
    h = hidden[..., None]
    c.signal = np.where(h, 0.0, c.signal).astype(np.float32)
    c.observed_mask = np.where(h, 0.0, c.observed_mask).astype(np.float32)
    c.validate()
    return c


def naive_prediction(signal: np.ndarray, visible: np.ndarray) -> np.ndarray:
    """Last visible value strictly before t inside the window; 0 (TRAIN mean) when none. (B, T)."""
    x = np.asarray(signal, np.float64)
    if x.ndim == 3:
        x = x[..., 0]
    vis = np.asarray(visible, bool)
    if vis.ndim == 3:
        vis = vis[..., 0]
    B, T = x.shape
    idx = np.where(vis, np.arange(T)[None, :], -1)
    last = np.maximum.accumulate(idx, axis=1)
    prev = np.concatenate([np.full((B, 1), -1), last[:, :-1]], axis=1)
    rows = np.arange(B)[:, None]
    return np.where(prev >= 0, x[rows, np.maximum(prev, 0)], 0.0)


def hidden_scores(x_clean: np.ndarray, x_hat: np.ndarray, hidden: np.ndarray, std: float, grid_hours=None) -> dict:
    x = np.asarray(x_clean, np.float64)[..., 0] if np.ndim(x_clean) == 3 else np.asarray(x_clean, np.float64)
    xh = np.asarray(x_hat, np.float64)[..., 0] if np.ndim(x_hat) == 3 else np.asarray(x_hat, np.float64)
    if x.shape != xh.shape or x.shape != hidden.shape:
        raise Refusal("SCORING_SHAPE_MISMATCH", f"{x.shape} {xh.shape} {hidden.shape}")
    err = (xh - x)[hidden]
    if err.size == 0:
        raise Refusal("NO_HIDDEN_POINTS")
    if not np.isfinite(err).all():
        raise Refusal("NON_FINITE_RECONSTRUCTION")
    out = {"mae": float(np.mean(np.abs(err))), "mse": float(np.mean(err ** 2)),
           "mae_orig": float(np.mean(np.abs(err)) * std), "hidden_points": int(err.size)}
    if grid_hours is not None:
        by_hour = []
        hrs = np.broadcast_to(grid_hours, hidden.shape)[hidden]
        for h in range(24):
            sel = hrs == h
            by_hour.append({"hour": h, "n": int(sel.sum()),
                            "mae": float(np.mean(np.abs(err[sel]))) if sel.any() else None})
        out["by_hour_utc"] = by_hour
    return out


# --------------------------------------------------------------------------- architecture
def build_models(hp: Hyper, calendar_dim: int = len(U.CALENDAR_SPEC)):
    """(encoder, decoder, training_model). Encoder: causal Conv1D, 24 -> 12 -> 6; decoder symmetric."""
    import keras
    L = keras.layers
    if hp.window != 4 * hp.latent_steps:
        raise Refusal("ARCHITECTURE", f"window {hp.window} must be 4 x latent_steps {hp.latent_steps}")
    F, k = hp.filters, hp.kernel_size
    inp = {"signal": keras.Input((hp.window, 1), name="signal"),
           "observed_mask": keras.Input((hp.window, 1), name="observed_mask"),
           "delta_time": keras.Input((hp.window, 1), name="delta_time"),
           "calendar": keras.Input((hp.window, calendar_dim), name="calendar")}
    x = L.Concatenate(name="series_channels")([inp["signal"], inp["observed_mask"], inp["delta_time"]])
    h = L.Conv1D(F, k, padding="causal", activation="relu", name="stem")(x)
    c = L.Conv1D(F, 1, name="calendar_proj")(inp["calendar"])
    h = L.Conv1D(F, 1, activation="relu", name="fuse")(L.Concatenate(name="fuse_concat")([h, c]))
    h = L.Conv1D(F, k, padding="causal", strides=2, activation="relu", name="down_24_12")(h)
    h = L.Conv1D(F, k, padding="causal", strides=2, activation="relu", name="down_12_6")(h)
    z = L.Conv1D(hp.latent_dim, 1, name="latent")(h)
    encoder = keras.Model(inp, z, name="fs4_encoder")
    if tuple(encoder.output.shape)[1:] != (hp.latent_steps, hp.latent_dim):
        raise Refusal("ARCHITECTURE", f"latent shape {encoder.output.shape}")
    zin = keras.Input((hp.latent_steps, hp.latent_dim), name="latent_in")
    d = L.Conv1D(F, k, padding="causal", activation="relu", name="dec_6")(zin)
    d = L.UpSampling1D(2, name="up_6_12")(d)
    d = L.Conv1D(F, k, padding="causal", activation="relu", name="dec_12")(d)
    d = L.UpSampling1D(2, name="up_12_24")(d)
    d = L.Conv1D(F, k, padding="causal", activation="relu", name="dec_24")(d)
    out = L.Conv1D(1, 1, name="reconstruction")(d)
    decoder = keras.Model(zin, out, name="fs4_decoder")
    training = keras.Model(inp, decoder(encoder(inp)), name="fs4_training")
    training.compile(optimizer=keras.optimizers.Adam(hp.learning_rate), loss="mse")
    return encoder, decoder, training


def seed_weights(models: Sequence, seed: int) -> None:
    """Deterministic numpy initialisation (glorot-uniform kernels, zero biases), device independent."""
    rng = np.random.default_rng(seed)
    for model in models:
        new = []
        for w in model.weights:
            shape = tuple(w.shape)
            if len(shape) >= 2:
                fan_in = int(np.prod(shape[:-1]))
                fan_out = int(shape[-1]) * int(np.prod(shape[:-2])) if len(shape) > 2 else int(shape[-1])
                limit = np.sqrt(6.0 / (fan_in + fan_out))
                new.append(rng.uniform(-limit, limit, size=shape).astype(np.float32))
            else:
                new.append(np.zeros(shape, np.float32))
        model.set_weights(new)


def weights_digest(models: Sequence) -> str:
    h = hashlib.sha256()
    for model in models:
        h.update(U.weights_sha256(model).encode())
    return h.hexdigest()


def reconstruct(training_model, batch: U.TemporalBatch) -> np.ndarray:
    return np.asarray(training_model.predict(batch.as_inputs(), batch_size=512, verbose=0), np.float32)


def fit_trained(training_model, encoder, decoder, fit_b: U.TemporalBatch, es_b: U.TemporalBatch,
                hp: Hyper, seed: int, es_hidden: np.ndarray, log=None) -> dict:
    """TRAIN-only masked reconstruction; early stopping on the purged ES tail; best checkpoint restored."""
    import keras
    es_input = corrupt(es_b, es_hidden)
    best, best_epoch, best_weights, wait = np.inf, -1, None, 0
    hist, digests, stop = [], [], "max_epochs"
    updates_at_best = 0
    t0 = time.perf_counter()
    for epoch in range(hp.max_epochs):
        h = hidden_mask(fit_b.observed_mask, _seed_from({"seed": seed, "epoch": epoch, "purpose": "fit_mask"}),
                        hp.hide_fraction)
        cin = corrupt(fit_b, h)
        training_model.fit(cin.as_inputs(), fit_b.signal, sample_weight=fit_b.observed_mask[..., 0],
                           batch_size=hp.batch_size, epochs=1, shuffle=True, verbose=0)
        rec = reconstruct(training_model, es_input)
        err = (rec[..., 0].astype(np.float64) - es_b.signal[..., 0])[es_hidden]
        loss = float(np.mean(err ** 2)) if err.size else float("nan")
        hist.append(loss)
        digests.append(weights_digest([encoder, decoder]))
        if log:
            log(f"epoch {epoch} es_hidden_mse={loss:.6f} updates={int(training_model.optimizer.iterations.numpy())}")
        if np.isfinite(loss) and loss < best:
            best, best_epoch, wait = loss, epoch, 0
            best_weights = [np.array(w) for w in training_model.get_weights()]
            updates_at_best = int(training_model.optimizer.iterations.numpy())
        else:
            wait += 1
            if wait >= hp.patience:
                stop = "patience"
                break
    if best_weights is None:
        raise U.TrainingDiverged("early-stopping loss never finite; no checkpoint to restore")
    final_digest = digests[-1]
    training_model.set_weights(best_weights)
    chosen = weights_digest([encoder, decoder])
    if chosen != digests[best_epoch]:
        raise Refusal("CHECKPOINT_RESTORE_MISMATCH")
    return {"stop_reason": stop, "epochs_run": len(hist), "chosen_epoch": best_epoch,
            "best_es_hidden_mse": float(best), "es_hidden_mse_history": hist,
            "updates": int(training_model.optimizer.iterations.numpy()), "updates_at_chosen": updates_at_best,
            "final_weights_sha256": final_digest, "chosen_weights_sha256": chosen,
            "restored_best_checkpoint": True, "fit_wall_seconds": time.perf_counter() - t0,
            "monitor": "hidden-point MSE on the purged TRAIN early-stopping tail (fixed mask)"}
